"""rename address

Revision ID: 46660f739deb
Revises: 421da49cd09c
Create Date: 2024-07-01 14:23:55.161924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46660f739deb'
down_revision = '421da49cd09c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
